configs:
  params:
    server.insecure: true
  cm:
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"

repoServer:
  env:
    - name: SOPS_AGE_KEY_FILE
      value: /sops/age/keys.txt
    - name: XDG_CONFIG_HOME
      value: /home/argocd
  volumes:
    - name: sops-age-key
      secret:
        secretName: sops-age-key
    - name: custom-tools
      emptyDir: {}
  volumeMounts:
    - name: sops-age-key
      mountPath: /sops/age
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: ["/bin/sh", "-c"]
      args:
        - cp /usr/local/bin/ksops /custom-tools/ksops
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
