all:
  hosts:
    vps:
      ansible_host: 91.134.142.175
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  vars:
    k3s_version: v1.34.4+k3s1
    domain: matltz.dev
    letsencrypt_email: "{{ vault_letsencrypt_email }}"
    registry_user: "{{ vault_registry_user }}"
    registry_password: "{{ vault_registry_password }}"
    grafana_password: "{{ vault_grafana_password }}"