all:
  hosts:
    vps:
      ansible_host: 91.134.142.175
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  vars:
    k3s_version: v1.34.4+k3s1
    letsencrypt_email: mathieu.leitzelman+encrypt@gmail.com
