apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry-maintenance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Mathieu135/infra.git
    targetRevision: main
    path: kubernetes/registry
  destination:
    server: https://kubernetes.default.svc
    namespace: registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
