# --- k3s ---
- name: Vérifier si k3s est déjà installé
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Installer k3s
  shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} sh -s - --disable traefik
  when: not k3s_binary.stat.exists
  become: yes

- name: Attendre que k3s soit prêt
  command: kubectl get nodes
  register: k3s_ready
  retries: 10
  delay: 5
  until: k3s_ready.rc == 0
  become: yes
  changed_when: false

# --- Kubeconfig pour l'utilisateur ---
- name: Créer le dossier .kube
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0700'

- name: Copier le Kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  become: yes

- name: Ajouter KUBECONFIG au bashrc
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: 'export KUBECONFIG=~/.kube/config'
    state: present

# --- Storage : /opt/k3s-data ---
- name: Créer le répertoire de stockage applicatif
  file:
    path: /opt/k3s-data
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Copier le ConfigMap local-path-config
  copy:
    dest: /tmp/local-path-config.yaml
    content: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: local-path-config
        namespace: kube-system
      data:
        config.json: |-
          {
            "nodePathMap": [
              {
                "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
                "paths": ["/opt/k3s-data"]
              }
            ]
          }

- name: Configurer local-path-provisioner vers /opt/k3s-data
  command: kubectl apply -f /tmp/local-path-config.yaml
  become: yes
  register: configmap_result
  changed_when: "'configured' in configmap_result.stdout"

- name: Redémarrer local-path-provisioner pour appliquer la config
  command: kubectl delete pod -n kube-system -l app=local-path-provisioner
  become: yes
  when: "'configured' in configmap_result.stdout"

# --- Helm ---
- name: Vérifier si Helm est déjà installé
  stat:
    path: /usr/local/bin/helm
  register: helm_binary

- name: Installer Helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  when: not helm_binary.stat.exists
  become: yes
