$ANSIBLE_VAULT;1.1;AES256
35363365633361353037393236333236643461313766373031393866353263373661643032663434
3966343463383462653733653262386234636666383763380a626637303530316331353765343032
66653664313263323230656335653433663339653732353732356163623839646336613764333266
3761663838613734640a653537373139393433653930643539663765303630323163353533326362
34356231363239363332366234623361393531333564663333353638376634366336636532343732
65313262643136316366326630386530663166643431356162633233653237303531383439643762
65333166323630346230306566633931336530623830656431396238326363333266343437663032
31656465313566376534643136326235356539313530313134333763313736353865616233643462
66336532303331663237313539613934323739643830396436383631623462313030393363393863
36633966643161353065303332663637626233303164613733353031346666613361666631343638
62333831323636323832356537653366323238303934643766666331353634323063633232306335
35343163623033626538
