$ANSIBLE_VAULT;1.1;AES256
62633363323863643562306332393963623862303035613663333733613739373835366661613135
3430303139306231663039366337373964663666366134650a623533323762663130316133643866
61396662326566656337383966313234303161346265363430653364613031333862366166656433
3936663331613739300a326664336134336134653563643138363235393263666534353737393338
61666262323736626332623839613235343762383235376266396333393566386232313062313434
33626536643764623764326230366133656234653363383965333432393261366438343333396537
39343866646336316436323131623334613536363265653034653064306538376164646561343931
35353936663434316365623566303138393966313534626233336436393034333836656430363833
36376565323938373331303134383938313231653164623734386237333237383938363963666363
61633331623961363834373165376339326437636230633737326262356537303762306264363136
62373035646263326436646435336561323662383537663766666266313938323461373237633537
35336536366165343432373436653133393266353931383332316464646334333735613738306365
37663635626562363237643538623234323837356431366261383063636334636166663566666163
37326635323166653231643238353166393333313765323464393865663238336364343037393262
37333963326336616161356137656335633534376533643536636437353336343633316164353330
39376630636334333461346538373933663333616161323638653331356465313666323461333434
65666533666239373737623962343463306235353932386366373165343731646137613336653763
34613331643536373231643363373464626466373834623961626662353738623938663361333962
64373436623065626533386663323230343062316636636465386437343739633561356366353035
62316564616339666533646561616262316665346562343135663733393561626361346130366634
36356265396231356633346239373466636164656531303966323661626638383734303264346462
36633436346438346461633964396430626664666663643132656166373938386438346163633437
30613936616335376366656564636132346563623831653330646435346535616461616636323536
33336437626337623336653931326666643038346436373366303939356638613636366631393434
64626562306439303236636438323430383264316262343464306563386237643638626466316331
33613436623066653963663536353634613434303838663230663937346333373130386332663933
316531326362376237396265313036316165
