$ANSIBLE_VAULT;1.1;AES256
36393534643930623365663861333535353466613631373064313139666232353036386262313063
6436316363663463326437366261353534633937623565330a396537633461666462616632396464
61353663303334313863336163616637643837643235623966306563393132623937306332363632
3163353062613339630a643666383133303361316539346538326431643366623336386334396235
64633366613639643265643962653734326538636163636133333865643036613766646236303831
30333332306161363336363363633164333662666134373837336662393038623864323532653065
32636462313661386635663464343039656434303066313030663133656562636564383932316635
39633461373434386363653137373165636466383932323733303336306435653464383262333236
33623237343039366132353338363962633237303762616633363362393839303734306638346537
66623966316163396233393465316530313162626265626433646166363136646631396239356566
39633963363637393733343933346661306561313631303261346664376364613137386630356133
64666661313333656162323436316538333230383735663736373961386235663234323233663662
65643034663033623565643761633830633331396661306464663836393533653930653230636335
61363338306434373332356463326334373263613761666261363338316230306461313038346131
31353865383465666336663563616235343330616438306436353836323964653839303562623230
63396637653562643637366431616135373734623730306463636531356465386662376336376662
33336166633739353338643832386365323362303039366465653730653335386134353535643763
65653564316638363531343532616539336661653837363337656538383438663461373131393462
30336634656261333965333465313265303433393037353131363135303736303161613630623832
62616539636137386662306231336162393439323965646436343935373733323264623131313235
6163
