apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - cronjob-pg-backup.yaml
  - deployment-frontend.yaml
  - deployment-backend.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - ingress.yaml
  - network-policy.yaml
  - prometheusrule-auth.yaml
generators:
  - ksops-generator.yaml
