---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: portfolio-secrets
  namespace: portfolio
spec:
  encryptedData:
    JWT_SECRET: AgC405FaIfOQ/pdzCcq1hH/GvqukdzGG5YaizkE4Fci9hUmxhDXgc4Oj/V6uAvfY10LHofqlKI9cnC90JVZECRSLszGFcuIhe4xYdxw7QmGcz6HppTiIOzmEJoRQfZT7HLDnQd4LZKlLYL9zyUO4mLgOlkJy+748N6Li/OhkiJJw+HxHWlwKj1HqIka6SItJSpuFzkgR99fn6+WNDHvkm4PPueJxgXlq6oRB1dNa/k9Fv7OMcTsIxnOwo9QUQFRoNQSuJaaUEb7tIUBq1Np8nNjTN6iYMtSbyKcmZClsKExBivXn0mYioJMY4PsLqcTOzQuxF7IMzCB2PpOSubXFokO6HISZj7+5wMv+lHN3H/QiGFk4PBGpb6CzcQzJXJv5XXtlcyWnToC4mvyk8LdRfrxwWrqjSD8vA5lhL+teuNTkMCu97p8SACYiGJ2+diAPKQvmHb7FOLp756Qpgu9h5NDcGBMpdZmkeLlCCiaW6CkwWu5Qws/GWo0GHyX6rmdxxvmuoFaQFFcJfsdnwQ/q1os7818al1LX61Q+XYXJdxfVVOzG5Mo4rcsB7/qfI/LaQMBA7/iDEf79B8ZroZLJe8GI0Cy+gKdjM5yDRKX9vuifCLApkJrx3Kkqm6IWEZfSi4PprkTTsTiVbg4JzMZHQj1xjqBlW/a3wdTnsIrM8qjXxy7qKaFUkPngamXuQm6edU1977DFg0YUSafgpg4o1g==
  template:
    metadata:
      name: portfolio-secrets
      namespace: portfolio
