apiVersion: v1
kind: Secret
metadata:
    name: portfolio-secrets
    namespace: portfolio
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:0LZh5ql7z9zREGlGcnAV9fBWPrGQJxcoTM7Tk9i4G8UYxNFLoYB9X9aUnf4=,iv:DDuX8CMl/FtQLScfWZe43AulD/7vJ7uwjXqDVnxOshM=,tag:bXtK2KW8BpH10hUdhDkshQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ELTJ24wNZNMvHvTtHUHj2z2+x4//SfEBywoaI20W2V8=,iv:FRDoCi1cLH1KvQd77SwXKcJ71mjTHHjeB/b9Kx+gZDU=,tag:Gci9Jqx85MIWs5KfHeOgiA==,type:str]
sops:
    age:
        - recipient: age1mcxcm4rwjfa4xhzdkrh7qnkcspdgvhffukvc8mpeuvrwm96pdysqwk8t9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvclZHSzE1NlBqVVFWYktp
            c25YUlZsUndIdExmNVhGbmIwRTQzaFJsL1NRCitkSVB1M3JHMjRiUy85QXlHRUZ4
            M2pRYXRia2wvNUVjY1V1d1dGWUhJWkkKLS0tIG4xYjRvYlI0dWpLWUpFdSt2K2tn
            dE9jWFBzOTd3NC9yTDJKK3JVbEFIUWMKOrq3EV1BIWF8NEX3N6aDsLhhEPU2Mco3
            mNWmbHbHTalMuNxngYfuAQPapKuX/ayahjP7zFb72OgOSMOOfWmG/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-20T21:09:53Z"
    mac: ENC[AES256_GCM,data:CRR9l7IfD1Ge13+J+50y/scK/rv9A5z9T72ntV6hHvFyxvMp+qQQVjf8qT722BitrIum5lAadtrH7ASxZHcwhRSIra7kGK6UQBdK1ga5cPSHUFo2kLNGAk4AYqlnuThLSSzaza+hZPB2VQjnebe19O71phqjN53J+rwefUTyre8=,iv:n2d48MnOafnIAJ4QM1Yr4L20OWrRiqFcrEeQUXbzfh8=,tag:/eo4nCBNvttGOJct1MIkvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
