apiVersion: v1
kind: Secret
metadata:
    name: portfolio-secrets
    namespace: portfolio
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:0LZh5ql7z9zREGlGcnAV9fBWPrGQJxcoTM7Tk9i4G8UYxNFLoYB9X9aUnf4=,iv:DDuX8CMl/FtQLScfWZe43AulD/7vJ7uwjXqDVnxOshM=,tag:bXtK2KW8BpH10hUdhDkshQ==,type:str]
sops:
    age:
        - recipient: age1mcxcm4rwjfa4xhzdkrh7qnkcspdgvhffukvc8mpeuvrwm96pdysqwk8t9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvclZHSzE1NlBqVVFWYktp
            c25YUlZsUndIdExmNVhGbmIwRTQzaFJsL1NRCitkSVB1M3JHMjRiUy85QXlHRUZ4
            M2pRYXRia2wvNUVjY1V1d1dGWUhJWkkKLS0tIG4xYjRvYlI0dWpLWUpFdSt2K2tn
            dE9jWFBzOTd3NC9yTDJKK3JVbEFIUWMKOrq3EV1BIWF8NEX3N6aDsLhhEPU2Mco3
            mNWmbHbHTalMuNxngYfuAQPapKuX/ayahjP7zFb72OgOSMOOfWmG/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-18T20:10:11Z"
    mac: ENC[AES256_GCM,data:8gb0xr/DSRlcpU8r6fNQTqm3EiyJrq/JAq5fTICUPlVPDH/UTgUAdnH7qCHPcqwqN/EjFqYBaXPQ2ZZ35ML86Awzf11eSatVFItCnoA5gjPy5+oCUYqOXqiETL0xkEuGKNW4VGMdg3M/RHWyRSAMwPsEu7wP+/gFhLm225FP7TQ=,iv:6PXI/4mKgSvGvMzQolKk4qzmofCA+hstoeg+VxzV1eg=,tag:s55udNBOsfp4PUkq/GGB/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
