apiVersion: v1
kind: Secret
metadata:
    name: portfolio-secrets
    namespace: portfolio
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:Ej/QtPh+NFGcn0/jtZBhj6jGNrf77TaSKgi5BaXu4wK7/HYxXw52Q6NQZlk=,iv:Z7IXWqPs5KOZpvCIM2CPe9I+927FMkcum873hyPM3HI=,tag:Fx0FzWPs49CiqUkkOXexhQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ahX7GTJ9Xg41WRJqSsLOCqkv+154lxbACVj5IcJ5STI=,iv:yi8wp16afqzcGcvta8bY8e1j08Xubz8p9Tp0U3RDSEs=,tag:RS1N2oIbjWUC5DqApaL84w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:TFA00DL7yfvd,iv:Z77OCBrnqmpkzdSj+WPp91CyHbbxq2Ao7XsRQhwp/4g=,tag:YE7sg2JWaSvf9P9m2Xf9vg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vvQ4TowrOUzNJ4eWTvauNHyEITUvLHlbyNugMfM/Bg==,iv:/K/C/RqXJuHmHJRVyykXxCgpe+OUSdClmUr69uwAgos=,tag:YJ49zWdsZmwxAsXRP/7oRg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:fQpEZ2hPk/LpZ2MQwUJBpCvfFmnNAuYOoVOHeo8lkIeMKGf6DIZKTsrJNQ7W9wjUXDSSV280qCKmRxGx96lHUarDn8F4zLDYnoBZ+95bx9bAy181tfJa2Q==,iv:PwOC9I0UjQi4tK6sFA5+HvQZdDPOym2W+cwLulDw4Hs=,tag:4uJ3rAH3RIVpUjE717/sPA==,type:str]
sops:
    age:
        - recipient: age1mcxcm4rwjfa4xhzdkrh7qnkcspdgvhffukvc8mpeuvrwm96pdysqwk8t9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OVhnd2FpSllMaHpvaFkz
            cU1nZ2ZuMm1UaFVEWTdxWVRZM1ZsNDljd2h3CkFDWWtxcUYvYmpuM0ZFbUdIa1Q5
            djUwcHo4UE1vS0FCSWUyeXdPclZFalkKLS0tIFQxSkMyUXJKTGtEOGI0UVhhbVJM
            STZLemNqb2gwL2FxTk5OT1N1WkcwSTgKGsTxTZzFg811nr12Ze2U94Wd+ER7GOVs
            w/yzw5ZXXR7scmA/ljtaKSxjfcc4WCXROox+BQHGtTRHOhbKibGX9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-21T08:51:53Z"
    mac: ENC[AES256_GCM,data:K61knI/vGyQxsN3Pf8EG+GOeCq0wZp5GMzZa3q4c3LzPsJM0kxYC7+yYLVTzhb20cDTVCUSmj54txjNhiltGN/7pbcSi/CDqsnm4LKJ1VFQUADFPAZ/QUznzqkXfZPmgV98zwoA3sGJTPpsCxEeWkDY1tcRmN9wKjaKH++/1Vdc=,iv:tDLFKlE+Hl2xKZH05SOUvp8s7QqV/cnqijNOF55Wq88=,tag:XDpEEB/AG4f6Ue7pxlkC4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
