apiVersion: v1
kind: Service
metadata:
  name: portfolio-postgres
  namespace: portfolio
spec:
  clusterIP: None
  selector:
    app: portfolio-postgres
  ports:
    - port: 5432
      targetPort: 5432
